// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: chunks.sql

package pggen

import (
	"context"
	"time"

	"github.com/lib/pq"
	pgvector "github.com/pgvector/pgvector-go"
)

const countChunksByKnowledgeBase = `-- name: CountChunksByKnowledgeBase :one
SELECT COUNT(*) FROM chunks WHERE knowledge_base_id = $1
`

func (q *Queries) CountChunksByKnowledgeBase(ctx context.Context, knowledgeBaseID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countChunksByKnowledgeBase, knowledgeBaseID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createChunk = `-- name: CreateChunk :exec
INSERT INTO chunks (
    id, knowledge_base_id, document_id, chunk_index, content,
    content_length, embedding, embedding_dimension
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateChunkParams struct {
	ID                 string          `json:"id"`
	KnowledgeBaseID    string          `json:"knowledge_base_id"`
	DocumentID         string          `json:"document_id"`
	ChunkIndex         int32           `json:"chunk_index"`
	Content            string          `json:"content"`
	ContentLength      int32           `json:"content_length"`
	Embedding          pgvector.Vector `json:"embedding"`
	EmbeddingDimension int32           `json:"embedding_dimension"`
}

func (q *Queries) CreateChunk(ctx context.Context, arg CreateChunkParams) error {
	_, err := q.db.ExecContext(ctx, createChunk,
		arg.ID,
		arg.KnowledgeBaseID,
		arg.DocumentID,
		arg.ChunkIndex,
		arg.Content,
		arg.ContentLength,
		arg.Embedding,
		arg.EmbeddingDimension,
	)
	return err
}

const deleteChunksByDocument = `-- name: DeleteChunksByDocument :exec
DELETE FROM chunks WHERE document_id = $1
`

func (q *Queries) DeleteChunksByDocument(ctx context.Context, documentID string) error {
	_, err := q.db.ExecContext(ctx, deleteChunksByDocument, documentID)
	return err
}

const searchChunks = `-- name: SearchChunks :many
SELECT id, knowledge_base_id, document_id, chunk_index, content,
       content_length, embedding_dimension, created_at,
       (1 - (embedding <=> $1))::float8 AS score
FROM chunks
WHERE knowledge_base_id = ANY($2::text[])
  AND embedding_dimension = $3
ORDER BY embedding <=> $1
LIMIT $4
`

type SearchChunksParams struct {
	QueryEmbedding     pgvector.Vector `json:"query_embedding"`
	KnowledgeBaseIds   []string        `json:"knowledge_base_ids"`
	EmbeddingDimension int32           `json:"embedding_dimension"`
	TopK               int32           `json:"top_k"`
}

type SearchChunksRow struct {
	ID                 string    `json:"id"`
	KnowledgeBaseID    string    `json:"knowledge_base_id"`
	DocumentID         string    `json:"document_id"`
	ChunkIndex         int32     `json:"chunk_index"`
	Content            string    `json:"content"`
	ContentLength      int32     `json:"content_length"`
	EmbeddingDimension int32     `json:"embedding_dimension"`
	CreatedAt          time.Time `json:"created_at"`
	Score              float64   `json:"score"`
}

// <=> 是 pgvector 的余弦「距离」（0=同向 2=反向），1 - 距离 = 余弦相似度，
// 和被删掉的 similarity.go 语义完全一致——分数跨迁移可比。
// 两个 WHERE 条件都不可省：knowledge_base_id 是 CLAUDE.md 大表查询强过滤
// 规则；embedding_dimension 过滤是因为混合维度共存一张表，<=> 对不同维度
// 向量直接报错。::text[] cast 也不可省——sqlc 生成的代码用 pq.Array 传字符
// 串数组，显式 cast 消除 PG 的类型推断歧义。
func (q *Queries) SearchChunks(ctx context.Context, arg SearchChunksParams) ([]SearchChunksRow, error) {
	rows, err := q.db.QueryContext(ctx, searchChunks,
		arg.QueryEmbedding,
		pq.Array(arg.KnowledgeBaseIds),
		arg.EmbeddingDimension,
		arg.TopK,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchChunksRow{}
	for rows.Next() {
		var i SearchChunksRow
		if err := rows.Scan(
			&i.ID,
			&i.KnowledgeBaseID,
			&i.DocumentID,
			&i.ChunkIndex,
			&i.Content,
			&i.ContentLength,
			&i.EmbeddingDimension,
			&i.CreatedAt,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
