// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: chunks.sql

package pggen

import (
	"context"
	"database/sql"
	"time"

	"github.com/lib/pq"
	pgvector "github.com/pgvector/pgvector-go"
)

const countChunksByDocumentVersion = `-- name: CountChunksByDocumentVersion :one
SELECT COUNT(*) FROM chunks WHERE document_id = $1 AND document_version = $2 AND is_published = true
`

type CountChunksByDocumentVersionParams struct {
	DocumentID      string `json:"document_id"`
	DocumentVersion int64  `json:"document_version"`
}

// reconciliation 恢复卡在 publishing 的文档时用它现查这次尝试实际发布了
// 多少行，写回 MySQL 的 chunk_count——reconciliation 和原 worker 不是同一
// 次调用，没有 worker 当时算出来的 len(pieces) 可用。
func (q *Queries) CountChunksByDocumentVersion(ctx context.Context, arg CountChunksByDocumentVersionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countChunksByDocumentVersion, arg.DocumentID, arg.DocumentVersion)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countChunksByKnowledgeBase = `-- name: CountChunksByKnowledgeBase :one
SELECT COUNT(*) FROM chunks WHERE knowledge_base_id = $1 AND is_published = true
`

// 只数已发布的——未发布的草稿版本不该出现在"这个知识库有多少分片"的统计里。
func (q *Queries) CountChunksByKnowledgeBase(ctx context.Context, knowledgeBaseID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countChunksByKnowledgeBase, knowledgeBaseID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createChunk = `-- name: CreateChunk :exec
INSERT INTO chunks (
    id, knowledge_base_id, document_id, chunk_index, content,
    content_length, embedding, embedding_dimension, document_version, is_published,
    document_name, page_number, section_title
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
`

type CreateChunkParams struct {
	ID                 string          `json:"id"`
	KnowledgeBaseID    string          `json:"knowledge_base_id"`
	DocumentID         string          `json:"document_id"`
	ChunkIndex         int32           `json:"chunk_index"`
	Content            string          `json:"content"`
	ContentLength      int32           `json:"content_length"`
	Embedding          pgvector.Vector `json:"embedding"`
	EmbeddingDimension int32           `json:"embedding_dimension"`
	DocumentVersion    int64           `json:"document_version"`
	IsPublished        bool            `json:"is_published"`
	DocumentName       string          `json:"document_name"`
	PageNumber         sql.NullInt32   `json:"page_number"`
	SectionTitle       sql.NullString  `json:"section_title"`
}

// 新版本 chunks 一律以 is_published=false 写入——"新版本写入"这一步不改变
// 任何已发布的旧版本可见性，发布是 PublishChunkVersion 单独一步。
// document_name 是处理时刻的 Document.FileName 快照（Citation 用的来源
// 展示名，见 pgmigrations 000003）；page_number/section_title 当前解析器
// 不产出可靠值，调用方一律传 NULL，不允许伪造。
func (q *Queries) CreateChunk(ctx context.Context, arg CreateChunkParams) error {
	_, err := q.db.ExecContext(ctx, createChunk,
		arg.ID,
		arg.KnowledgeBaseID,
		arg.DocumentID,
		arg.ChunkIndex,
		arg.Content,
		arg.ContentLength,
		arg.Embedding,
		arg.EmbeddingDimension,
		arg.DocumentVersion,
		arg.IsPublished,
		arg.DocumentName,
		arg.PageNumber,
		arg.SectionTitle,
	)
	return err
}

const deleteChunksByDocument = `-- name: DeleteChunksByDocument :exec
DELETE FROM chunks WHERE document_id = $1
`

// 整份文档删除用（DeleteDocument）：不分版本、不看发布状态，全部清空。
func (q *Queries) DeleteChunksByDocument(ctx context.Context, documentID string) error {
	_, err := q.db.ExecContext(ctx, deleteChunksByDocument, documentID)
	return err
}

const deleteChunksByDocumentVersion = `-- name: DeleteChunksByDocumentVersion :exec
DELETE FROM chunks WHERE document_id = $1 AND document_version = $2
`

type DeleteChunksByDocumentVersionParams struct {
	DocumentID      string `json:"document_id"`
	DocumentVersion int64  `json:"document_version"`
}

// 精确删除某一个 version 的 chunks——CAS 发布网关被拒绝（version 已过期）
// 时，worker 用它清理自己刚写入、永远不会被发布的那批草稿行。
func (q *Queries) DeleteChunksByDocumentVersion(ctx context.Context, arg DeleteChunksByDocumentVersionParams) error {
	_, err := q.db.ExecContext(ctx, deleteChunksByDocumentVersion, arg.DocumentID, arg.DocumentVersion)
	return err
}

const deleteObsoleteChunkVersions = `-- name: DeleteObsoleteChunkVersions :exec
DELETE FROM chunks WHERE document_id = $1 AND document_version <> $2
`

type DeleteObsoleteChunkVersionsParams struct {
	DocumentID      string `json:"document_id"`
	DocumentVersion int64  `json:"document_version"`
}

// 发布步骤的"清理旧版本"半部分：删掉除了刚发布的这个 version 之外的所有
// 行。和下面 PublishChunkVersion 一起在同一个 PG 事务里调用（见
// repository.go 的 publishDocumentVersion），保证 PG 内部不会出现"新旧
// 同时可见"或者"新旧都不可见"的中间态。
func (q *Queries) DeleteObsoleteChunkVersions(ctx context.Context, arg DeleteObsoleteChunkVersionsParams) error {
	_, err := q.db.ExecContext(ctx, deleteObsoleteChunkVersions, arg.DocumentID, arg.DocumentVersion)
	return err
}

const publishChunkVersion = `-- name: PublishChunkVersion :exec
UPDATE chunks SET is_published = true WHERE document_id = $1 AND document_version = $2
`

type PublishChunkVersionParams struct {
	DocumentID      string `json:"document_id"`
	DocumentVersion int64  `json:"document_version"`
}

// 发布步骤的"发布新版本"半部分。
func (q *Queries) PublishChunkVersion(ctx context.Context, arg PublishChunkVersionParams) error {
	_, err := q.db.ExecContext(ctx, publishChunkVersion, arg.DocumentID, arg.DocumentVersion)
	return err
}

const searchKeywordChunks = `-- name: SearchKeywordChunks :many
SELECT id, knowledge_base_id, document_id, chunk_index, content,
       content_length, embedding_dimension, created_at,
       document_name, page_number, section_title,
       word_similarity($1, content)::float8 AS score
FROM chunks
WHERE knowledge_base_id = ANY($2::text[])
  AND is_published = true
  AND $1 <> ''
  AND $1 <% content
ORDER BY word_similarity($1, content) DESC, id ASC
LIMIT $3
`

type SearchKeywordChunksParams struct {
	QueryText        string   `json:"query_text"`
	KnowledgeBaseIds []string `json:"knowledge_base_ids"`
	CandidateK       int32    `json:"candidate_k"`
}

type SearchKeywordChunksRow struct {
	ID                 string         `json:"id"`
	KnowledgeBaseID    string         `json:"knowledge_base_id"`
	DocumentID         string         `json:"document_id"`
	ChunkIndex         int32          `json:"chunk_index"`
	Content            string         `json:"content"`
	ContentLength      int32          `json:"content_length"`
	EmbeddingDimension int32          `json:"embedding_dimension"`
	CreatedAt          time.Time      `json:"created_at"`
	DocumentName       string         `json:"document_name"`
	PageNumber         sql.NullInt32  `json:"page_number"`
	SectionTitle       sql.NullString `json:"section_title"`
	Score              float64        `json:"score"`
}

// pg_trgm 字符级 trigram/word-similarity 关键词检索（lexical search）——
// 明确不是 BM25：BM25 需要真正的分词 + 词频/逆文档频率统计，pg_trgm 只是
// 字符 n-gram 相似度，中英文都能用但不做语言学分词，也不做真正的相关性
// 排序模型。见 pgmigrations 000004 的索引和阈值说明。
//
// 不依赖 embedding，因此没有 embedding_dimension 过滤——这正是关键词检索
// 在 embedding 服务失败/超时时仍能独立返回结果的原因（见 service.go 的
// Retrieve：向量一路失败只跳过对应 embedding model 分组，关键词一路继续）。
// knowledge_base_id / is_published 两个过滤的必要性和 SearchVectorChunks
// 相同：大表强过滤规则、未发布草稿版本永不可检索。
//
// query_text <> ” 是防御性的第二道闸——Go 层 Retrieve/searchKeywordChunks
// 已经在空 query 时直接短路不落库查询，这里再挡一层，防止将来有调用方
// 绕开 Go 层校验时，<% 空串在语义上退化成"什么都不过滤"从而让全表都
// 变成候选。
// <% 走 idx_chunks_content_trgm 这个 GIN 索引过滤候选集（判定阈值见
// pgmigrations 000004 里对 pg_trgm.word_similarity_threshold 的说明）；
// ORDER BY 里的 word_similarity() 只对索引已经筛出的候选重新计算一次精确
// 分数用于排序，而不是对全表算。candidate_k 是硬上限，防止候选集无界增长。
func (q *Queries) SearchKeywordChunks(ctx context.Context, arg SearchKeywordChunksParams) ([]SearchKeywordChunksRow, error) {
	rows, err := q.db.QueryContext(ctx, searchKeywordChunks, arg.QueryText, pq.Array(arg.KnowledgeBaseIds), arg.CandidateK)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchKeywordChunksRow{}
	for rows.Next() {
		var i SearchKeywordChunksRow
		if err := rows.Scan(
			&i.ID,
			&i.KnowledgeBaseID,
			&i.DocumentID,
			&i.ChunkIndex,
			&i.Content,
			&i.ContentLength,
			&i.EmbeddingDimension,
			&i.CreatedAt,
			&i.DocumentName,
			&i.PageNumber,
			&i.SectionTitle,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchVectorChunks = `-- name: SearchVectorChunks :many
SELECT id, knowledge_base_id, document_id, chunk_index, content,
       content_length, embedding_dimension, created_at,
       document_name, page_number, section_title,
       (1 - (embedding <=> $1))::float8 AS score
FROM chunks
WHERE knowledge_base_id = ANY($2::text[])
  AND embedding_dimension = $3
  AND is_published = true
ORDER BY embedding <=> $1, id ASC
LIMIT $4
`

type SearchVectorChunksParams struct {
	QueryEmbedding     pgvector.Vector `json:"query_embedding"`
	KnowledgeBaseIds   []string        `json:"knowledge_base_ids"`
	EmbeddingDimension int32           `json:"embedding_dimension"`
	TopK               int32           `json:"top_k"`
}

type SearchVectorChunksRow struct {
	ID                 string         `json:"id"`
	KnowledgeBaseID    string         `json:"knowledge_base_id"`
	DocumentID         string         `json:"document_id"`
	ChunkIndex         int32          `json:"chunk_index"`
	Content            string         `json:"content"`
	ContentLength      int32          `json:"content_length"`
	EmbeddingDimension int32          `json:"embedding_dimension"`
	CreatedAt          time.Time      `json:"created_at"`
	DocumentName       string         `json:"document_name"`
	PageNumber         sql.NullInt32  `json:"page_number"`
	SectionTitle       sql.NullString `json:"section_title"`
	Score              float64        `json:"score"`
}

// Phase 3 前叫 SearchChunks——引入 SearchKeywordChunks 之后改名以便和它
// 对称、消歧义，语义完全不变。<=> 是 pgvector 的余弦「距离」（0=同向
// 2=反向），1 - 距离 = 余弦相似度，和被删掉的 similarity.go 语义完全
// 一致——分数跨迁移可比。
// 三个 WHERE 条件都不可省：knowledge_base_id 是 CLAUDE.md 大表查询强过滤
// 规则；embedding_dimension 过滤是因为混合维度共存一张表，<=> 对不同维度
// 向量直接报错；is_published 过滤是版本可见性网关——未发布的草稿版本永远
// 不能被检索命中，即使已经物理写入。::text[] cast 也不可省——sqlc 生成的
// 代码用 pq.Array 传字符串数组，显式 cast 消除 PG 的类型推断歧义。
// document_name/page_number/section_title 是 Citation V1 需要的来源
// metadata，随 chunk 一起返回给 conversation 层，knowledge 自己不解释它们。
// top_k 由调用方传入——Hybrid Search 场景下调用方传的是 candidateK（比
// 最终 topK 更宽的候选窗口，给 RRF 融合留排序空间），不是最终 topK 本身。
// ORDER BY 第二个键 id ASC 是稳定兜底：<=> 距离相同时 PostgreSQL 不保证
// 返回顺序，而 rrfFuse（hybrid.go）把这个结果切片的位置索引当成 RRF 的
// rank——距离相同却顺序不定，会让同一批候选在两次调用之间拿到不同的
// rank，进而拿到不同的 fusionScore，最终排序不稳定。id 是主键，任何两行
// 都不会相等，兜底到底。
func (q *Queries) SearchVectorChunks(ctx context.Context, arg SearchVectorChunksParams) ([]SearchVectorChunksRow, error) {
	rows, err := q.db.QueryContext(ctx, searchVectorChunks,
		arg.QueryEmbedding,
		pq.Array(arg.KnowledgeBaseIds),
		arg.EmbeddingDimension,
		arg.TopK,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchVectorChunksRow{}
	for rows.Next() {
		var i SearchVectorChunksRow
		if err := rows.Scan(
			&i.ID,
			&i.KnowledgeBaseID,
			&i.DocumentID,
			&i.ChunkIndex,
			&i.Content,
			&i.ContentLength,
			&i.EmbeddingDimension,
			&i.CreatedAt,
			&i.DocumentName,
			&i.PageNumber,
			&i.SectionTitle,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
