// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package pggen

import (
	"database/sql"
	"time"

	pgvector "github.com/pgvector/pgvector-go"
)

type Chunk struct {
	ID                 string          `json:"id"`
	KnowledgeBaseID    string          `json:"knowledge_base_id"`
	DocumentID         string          `json:"document_id"`
	ChunkIndex         int32           `json:"chunk_index"`
	Content            string          `json:"content"`
	ContentLength      int32           `json:"content_length"`
	Embedding          pgvector.Vector `json:"embedding"`
	EmbeddingDimension int32           `json:"embedding_dimension"`
	CreatedAt          time.Time       `json:"created_at"`
	DocumentVersion    int64           `json:"document_version"`
	IsPublished        bool            `json:"is_published"`
	DocumentName       string          `json:"document_name"`
	PageNumber         sql.NullInt32   `json:"page_number"`
	SectionTitle       sql.NullString  `json:"section_title"`
	PageEnd            sql.NullInt32   `json:"page_end"`
}
