// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package pggen

import (
	"context"
)

type Querier interface {
	CountChunksByKnowledgeBase(ctx context.Context, knowledgeBaseID string) (int64, error)
	CreateChunk(ctx context.Context, arg CreateChunkParams) error
	DeleteChunksByDocument(ctx context.Context, documentID string) error
	// <=> 是 pgvector 的余弦「距离」（0=同向 2=反向），1 - 距离 = 余弦相似度，
	// 和被删掉的 similarity.go 语义完全一致——分数跨迁移可比。
	// 两个 WHERE 条件都不可省：knowledge_base_id 是 CLAUDE.md 大表查询强过滤
	// 规则；embedding_dimension 过滤是因为混合维度共存一张表，<=> 对不同维度
	// 向量直接报错。::text[] cast 也不可省——sqlc 生成的代码用 pq.Array 传字符
	// 串数组，显式 cast 消除 PG 的类型推断歧义。
	SearchChunks(ctx context.Context, arg SearchChunksParams) ([]SearchChunksRow, error)
}

var _ Querier = (*Queries)(nil)
